#!/usr/bin/env python

##HACKABOT_HELP##
# Roll a single 20-sided die
# !1d20
##HACKABOT_HELP##

import os
import random
import string
import sys

# import hackabot utility classes
from command import Command

class OneDTwenty(Command):
    """
    Rolls a single 20-sided die and reports the results
    """

    def __init__(self):

        # call the base constructor to set up everything
        super(OneDTwenty, self).__init__('1d20')

    def main(self):

        # give sendnext command
        print >> sys.stdout, "sendnext"

        # dump the data we parsed
        print >> sys.stdout, random.randint(1,20)

        return None


if __name__ == "__main__":
    cmd = OneDTwenty()
    sys.exit(cmd.main())
