#!/usr/bin/env python

##HACKABOT_HELP##
# Get the answers to life!
# !8ball
##HACKABOT_HELP##

import os
import random
import re
import string
import sys

# hackabot helper classes
from command import Command

class Eightball(Command):
    """
    Emulates the 8-ball toy
    """

    answers = (
"""     ___
    /   \\
   /     \\
  / IT IS \\
 / CERTAIN \\
/           \\
\\___________/
""",
"""     ___
    /   \\
   /     \\
  /  MY   \\
 / SOURCES \\
/  SAY  NO  \\
\\___________/
""",
"""     ___
    /   \\
   /     \\
  /  MY   \\
 / SOURCES \\
/  SAY YES  \\
\\___________/
""",
""" ___________
/           \\
\\   MOST    /
 \\ LIKELY  /
  \\  NOT  /
   \\     /
    \\___/
""",
""" ___________
/           \\
\\           /
 \\ UMMM..  /
  \\   NO  /
   \\     /
    \\___/
""",
""" ___________
/           \\
\\  WITHOUT  /
 \\    A    /
  \\ DOUBT /
   \\     /
    \\___/
""",
"""     ___
    /   \\
   /     \\
  / VERY  \\
 /         \\
/  DOUBTFUL \\
\\___________/
""",
"""     ___
    /   \\
   /     \\
  /       \\
 /    NO   \\
/           \\
\\___________/
 """,
"""     ___
    /   \\
   /     \\
  /       \\
 /   YES   \\
/           \\
\\___________/
""",
""" ___________
/           \\
\\     I     /
 \\  DON'T  /
  \\ CARE  /
   \\     /
    \\___/
""",
""" ___________
/           \\
\\           /
 \\  HECK   /
  \\  YEA! /
   \\     /
    \\___/
""")

    def __init__(self):
        super(Eightball, self).__init__('8ball')

    def main(self):

        self._get_log().debug('8ball running')
        print >> sys.stdout, "sendnext"
        print >> sys.stdout, Eightball.answers[ random.randint(0, len( Eightball.answers ) ) ]
        sys.stdout.flush()
        self._get_log().debug('8ball done')
        
if __name__ == "__main__":
    cmd = Eightball()
    sys.exit(cmd.main())
