#!/usr/local/bin/bash

##HACKABOT_HELP##
# About this Bot
# !about
##HACKABOT_HELP##

echo "sendnext"
echo "Hackabot :: Version [something between 0 and 1]"
echo "Originally From: http://github.com/MostAwesomeDude/hackabot"
echo "Hg Repo: http://bitbucket.org/wookie/hackabot/"
