#!/usr/bin/env python

##HACKABOT_HELP##
# Send a /me message
# !action [#chan] something to do
##HACKABOT_HELP##

import os
import re
import sys

from command import Command

class Action(Command):

    def __init__(self):

        # call the base constructor to set up everything
        super(Action, self).__init__('action')

    def main(self):

        if re.match(r'^(#\S+)\s+(.+)$', self._msg):
            c = re.match(r'^(#\S+)\s+(.+)$', self._msg)
            print >> sys.stdout, 'to %s' % c.group(1)
            print >> sys.stdout, 'me %s' % c.group(2)
        elif re.match(r'^(.+)$', self._msg):
            c = re.match(r'^(.+)$', self._msg)
            print >> sys.stdout, 'me %s' % c.group(1)
        else:
            self._print_help(os.path.realpath(__file__))
            return 1

        return None


if __name__ == "__main__":
    cmd = Action()
    sys.exit(cmd.main())
