#!/usr/bin/env python

##HACKABOT_HELP##
# Run Administrative tasks
# !admin join #chan | part #chan | channels | nick name | quit msg | reload
##HACKABOT_HELP##

import os
import re
import string
import sys

from command import Command
from control import Channels

class Admin(Command):
    """
    Runs administrative tasks
    """

    def __init__(self):
        super(Admin, self).__init__('admin')

    def main(self):
        
        # get the command and arguments
        c = re.match(r'(\S*)\s*(.*)', self._msg)
        cmd = c.group(1)
        arg = c.group(2)

        if cmd.lower() in ('quit', 'nick', 'join', 'part'):
            print >> sys.stdout, "%s %s" % (cmd, arg)
        elif cmd.lower() == 'reload':
            print >> sys.stdout, "reloadacl"
        elif cmd.lower() == 'channels':
            c = Channels()
            print >> sys.stdout, 'send I am currently in: %s' % ' '.join(c)

if __name__ == "__main__":
    cmd = Admin()
    sys.exit(cmd.main())
