#!/usr/bin/env python

##HACKABOT_HELP##
# Run Administrative tasks
# !admin join #chan | part #chan | nick name | quit msg
##HACKABOT_HELP##

import string
import sys
import os
import re
from hackabot import *

class Admin(hackabot.Command):
    """
    Runs administrative tasks
    """

    def __init__(self):
        super(Admin, self).__init__('admin')

    def main(self):
        
        # get the command and arguments
        c = re.match(r'(\S*)\s*(.*)', self._msg)
        cmd = c.group(1)
        arg = c.group(2)

        if cmd.lower() in ('quit', 'nick', 'join', 'part'):
            print >> sys.stdout, "%s %s" % (cmd, arg)

if __name__ == "__main__":
    cmd = Admin()
    sys.exit(cmd.main())
