#!/usr/bin/env python

##HACKABOT_HELP##
# Flips a coin and reports heads or tails
# !coinflip
##HACKABOT_HELP##

import os
import random
import string
import sys

from command import Command

class CoinFlip(Command):
    """
    An example command using new command writing tools.
    """

    def __init__(self):

        # call the base constructor to set up everything
        super(CoinFlip, self).__init__()

    def main(self):
        """
        example handler function
        """

        val = random.randint(0, 99)

        # give sendnext command
        print >> sys.stdout, "sendnext"

        if val >= 50:
            print >> sys.stdout, "heads"
        else:
            print >> sys.stdout, "tails"

        return None


if __name__ == "__main__":
    cmd = CoinFlip()
    sys.exit(cmd.main())
