#!/usr/bin/env python

##HACKABOT_HELP##
# List and get help for the available commands
# !help [command name]
##HACKABOT_HELP##

import os
import re
import string
import sys

from command import Command

class Help(Command):
    """
    Displays help for commands
    """

    def __init__(self):
        super(Help, self).__init__('help')

    def main(self):

        # echo the argument back to the current 'to' target 
        print >> sys.stdout, 'sendnext'
        print >> sys.stdout, '%s' % self._msg

if __name__ == "__main__":
    cmd = Help()
    sys.exit(cmd.main())
