#!/usr/bin/env python

##HACKABOT_HELP##
# Set up a ping that will fire when the nick is next seen
# !pingsnipe <nick> <ping message>
##HACKABOT_HELP##

import os
import re
import sys

from command import Command
from models import Note

class PingSnipe(Command):

    def __init__(self):

        # call the base constructor to set up everything
        super(PingSnipe, self).__init__('pingsnipe')

    def _add_note(self, to, msg, chan=None):

        # get the connection
        store = self._get_database_connection()

        chan = ''
        if re.match(r'^(#\S+)$', self._to):
            c = re.match(r'^(#\S+)$', self._to)
            chan = c.group(1)

        # create the new record
        note = Note(self._nick, to, chan, msg)

        # add it
        store.add(note)

        # flush and commit
        store.flush()
        store.commit()

        print >> sys.stdout, 'to %s' % self._to
        print >> sys.stdout, 'send ping snipe to %s is queued...' % to

    def main(self):

        if re.match(r'^(\S+)\s+(.+)$', self._msg):
            c = re.match(r'^(\S+)\s+(.+)$', self._msg)
           
            # add the note
            self._add_note(c.group(1), c.group(2))

        else:
            self._print_help(os.path.realpath(__file__))
            return 1

        return None;
 
if __name__ == "__main__":
    cmd = PingSnipe()
    sys.exit(cmd.main())
