#!/usr/bin/python

##HACKABOT_HELP##
# Sample command that uses new hackabot python command tools
# !ptest
##HACKABOT_HELP##

import string
import sys
import os
from hackabot.command import Command

class PTest(Command):
    """
    An example command using new command writing tools.
    """

    def __init__(self):

        # call the base constructor to set up everything
        super(PTest, self).__init__()

    def main(self):
        """
        example handler function
        """

        # give sendnext command
        print >> sys.stdout, "sendnext"

        # dump the data we parsed
        print >> sys.stdout, "command details:"
        print >> sys.stdout, "\tevent type: " + str(self._event_type)
        print >> sys.stdout, "\tnick: " + str(self._nick)
        print >> sys.stdout, "\tuser: " + str(self._user)
        print >> sys.stdout, "\thost: " + str(self._host)
        print >> sys.stdout, "\tmsg: " + str(self._msg)
        print >> sys.stdout, "\tto: " + str(self._to)

        return None


if __name__ == "__main__":
    cmd = PTest()
    sys.exit(cmd.main())
