#!/usr/bin/env python

##HACKABOT_HELP##
# Send a message
# !sayto #chan something to say
##HACKABOT_HELP##

import os
import re
import sys

from command import Command
from control import ChannelNames

class SayTo(Command):

    def __init__(self):

        # call the base constructor to set up everything
        super(SayTo, self).__init__('sayto')

    def _nick_allowed(self, chan):

        # get the list of names from the specified channel
        cn = ChannelNames(chan)

        # check if the name is in the channel
        return (self._nick in cn)

    def main(self):

        if re.match(r'^(#\S+)\s+(.+)$', self._msg):
            c = re.match(r'^(#\S+)\s+(.+)$', self._msg)
            chan = c.group(1)
            msg = c.group(2)
            if self._nick_allowed(chan):
                print >> sys.stdout, 'to %s' % chan
                print >> sys.stdout, 'send from %s: %s' % (self._nick, msg)
            else:
                print >> sys.stdout, 'send You are not in that channel, so I won\'t talk for you in there.'
        else:
            self._print_help(os.path.realpath(__file__))
            return 1

        return None


if __name__ == "__main__":
    cmd = SayTo()
    sys.exit(cmd.main())
