#!/usr/bin/env python

##HACKABOT_HELP##
# Shows the nick of the person who last changed the topic and when
# !topicinfo [channel]
##HACKABOT_HELP##

import sys
import os
import re

from command import Command
from control import ChannelTopicInfo

class TopicInfo(Command):
    
    def __init__(self):

        # call the base constructor to set up everything
        super(TopicInfo, self).__init__('TopicInfo')

    def main(self):

        # get the argument
        c = re.match(r'\s*(\S*).*', self._msg)
        chan = c.group(1)

        if not len(chan):
            self._print_help(os.path.realpath(__file__))
            return None
           
        # get channel names 
        ti = ChannelTopicInfo(chan)
        
        # give sendnext command
        print >> sys.stdout, "sendnext"

        # print out the names
        print >> sys.stdout, 'Topic was last changed by %s on %s' % (ti._nick, ti._date)

        return None


if __name__ == "__main__":
    cmd = TopicInfo()
    sys.exit(cmd.main())
