#!/usr/bin/env python

##HACKABOT_HELP##
# Command shows the bot's uptime
# !uptime
##HACKABOT_HELP##

import datetime
import os
import sys

from command import Command

class Uptime(Command):
    
    def __init__(self):

        # call the base constructor to set up everything
        super(Uptime, self).__init__('uptime')

    def _get_days(self):
        if self._days == 1:
            return ' %d day,' % self._days
        return ' %d days,' % self._days

    def _get_hours(self):
        if self._hours == 1:
            return ' %d hour,' % self._hours
        return ' %d hours,' % self._hours

    def _get_minutes(self):
        if self._minutes == 1:
            return ' %d minute,' % self._minutes
        return ' %d minutes,' % self._minutes

    def _get_seconds(self):
        if self._seconds == 1:
            return ' %d second' % self._seconds
        return' %d seconds' % self._seconds

    def main(self):

        # get the path to the start file
        start_file = self._get_full_path(self._get_config()['startfile'])

        f = open(start_file, 'r')
        start_timestamp = float(f.read())
        f.close()

        dtnow = datetime.datetime.utcnow()
        dtstart = datetime.datetime.utcfromtimestamp(start_timestamp)
        diff = dtnow - dtstart

        self._days = diff.days
        self._hours = diff.seconds / 3600
        self._minutes = (diff.seconds % 3600) / 60
        self._seconds = (diff.seconds % 60)

        if self._days > 0:
            uptime = 'send up%s%s%s%s' % (self._get_days(), self._get_hours(), self._get_minutes(), self._get_seconds())
        elif self._hours > 0:
            uptime = 'send up%s%s%s' % (self._get_hours(), self._get_minutes(), self._get_seconds())
        elif self._minutes > 0:
            uptime = 'send up%s%s' % (self._get_minutes(), self._get_seconds())
        else:
            uptime = 'send up%s' % self._get_seconds()

        # give send command
        print >> sys.stdout, uptime

        return None


if __name__ == "__main__":
    cmd = Uptime()
    sys.exit(cmd.main())
