#!/usr/bin/env python

##HACKABOT_HELP##
# Send a woof to somebody see: http://www.youtube.com/watch?v=ytc9-wGCHW0
# !woof nick something to say
##HACKABOT_HELP##

import datetime
import os
import random
import re
import sys

from storm.expr import Asc,Desc,And,Or

from command import Command
from control import AllNames

class Woof(Command):

    def __init__(self):

        # call the base constructor to set up everything
        super(Woof, self).__init__('woof')

    def _woof(self, to, msg):

        # figure out which channels the person is currently in
        an = AllNames()
        chans = []
        if an._channels_by_name.has_key(to):
            chans = an._channels_by_name[to]

        for chan in chans:
            self._log.debug('sending woof to %s on %s' % (to, chan))
            print >> sys.stdout, 'to %s' % chan
            print >> sys.stdout, 'send ping %s' % to
            print >> sys.stdout, 'send woof from %s: %s' % (self._nick, msg)

    def main(self):

        # get where they are checking
        if re.match(r'^\s*(\S+)\s+(.+)$', self._msg):
            c = re.match(r'^\s*(\S+)\s+(.+)$', self._msg)
            to = c.group(1)
            msg = c.group(2)
        else:
            print >> sys.stdout, 'send missing parameter'
            self._print_help(os.path.realpath(__file__))
            return 1

        self._woof(to, msg)

if __name__ == "__main__":
    cmd = Woof()
    sys.exit(cmd.main())
