#!/usr/bin/env python

##HACKABOT_HELP##
# Who want's a Zima?
# !zima [#chan] nick
##HACKABOT_HELP##

import os
import re
import sys

from command import Command

class Zima(Command):

    def __init__(self):

        # call the base constructor to set up everything
        super(Zima, self).__init__('zima')

    def main(self):

        if re.match(r'^(#\S+)\s+(.+)$', self._msg):
            c = re.match(r'^(#\S+)\s+(.+)$', self._msg)
            print >> sys.stdout, 'to %s' % c.group(1)
            print >> sys.stdout, 'send Waah waah! %s wants a Zima!' % c.group(2)
        else:
            print >> sys.stdout, 'send Waah waah! %s wants a Zima!' % self._msg

        return None


if __name__ == "__main__":
    cmd = Zima()
    sys.exit(cmd.main())
