#!/usr/bin/env python

"""
This is the logging hook.  All messages are logged to the specified database.
"""

import sys

# import hackabot utility classes
from hook import Hook
from models import LogEntry

class Log(Hook):

    def __init__(self):

        # call the base constructor to set up everything
        super(Log, self).__init__('log')

    def main(self):

        try:
            # get the connection
            store = self._get_database_connection()

            # create the new log item
            e = LogEntry(self._nick, self._to, self._msg, 0, self._event_type)

            # add it to the database
            store.add(e)

            # commit it
            store.flush()
            store.commit()
            
            self._log.debug('Log successfully logged to database...(id: %d)' % e.id)
       
        except Exception, err:
            self._log.warn('Log hook: %s' % err)

        return None

if __name__ == "__main__":
    hook = Log()
    sys.exit(hook.main())
