#!/usr/bin/env python

"""
This is the logging hook.  All messages are logged to the specified database.
"""

import os
import sys

# import hackabot utility classes
from hook import Hook

class Log(Hook):

    # Log queries
    Q = { 
        'mysql': { 
            'log': ''
        },
        'sqlite': { 
            'log' : 'INSERT INTO log (date, text, chan, nick, type) VALUES (date("now"),?,?,?,?)'
        }
    }

    def __init__(self):

        # call the base constructor to set up everything
        super(Log, self).__init__('log')

        # set up our queries
        self._queries = Log.Q[self._db.lower()]

    def main(self):

        try:
            # get the connection
            conn = self._get_database_connection()

            # start a cursor
            c = conn.cursor()

            # run the query
            params = (self._msg, self._to, self._nick, self._event_type)
            c.execute(self._queries['log'], params)

            # commit the change
            conn.commit()

            # clean up
            c.close()
            conn.close()

            self._log.debug('Log successfully logged to database...')
       
        except Exception, err:
            self._log.warn('Log hook: %s' % err)

        return None

if __name__ == "__main__":
    hook = Log()
    sys.exit(hook.main())
