#!/usr/bin/env python

"""
This is the hook for tracking ++/-- scores
"""

from datetime import datetime
import re
import sys

# import hackabot utility classes
from hook import Hook
from models import ScoreEntry
from control import ChannelNames

class Score(Hook):

    def __init__(self):

        # call the base constructor to set up everything
        super(Score, self).__init__('score')

    def _nick_in_channel(self, chan, nick):
        # get the list of names from the specified channel
        cn = ChannelNames(chan)

        # check if hte name is in the channel
        return (nick in cn)

    def main(self):

        delta = 0
        name = None

        if re.match(r'\s+!.*', self._msg):
            # we don't care about ! commands
            return None

        if re.match(r'^\s*(\S+)\+\+\s*$', self._msg):
            c = re.match(r'^\s*(\S+)\+\+\s*$', self._msg)
            name = c.group(1)
            delta = 1

        if re.match(r'^\s*(\S+)\-\-\s*$', self._msg):
            c = re.match(r'^\s*(\S+)\-\-\s*$', self._msg)
            name = c.group(1)
            delta = -1

        # if it wasn't a ++/-- message, then we don't adjust any scores
        if name is None or (not self._nick_in_channel(self._to, name)):
            self._log.debug('Score can\'t be recorded for non-nick')
            return None

        if self._nick.lower() == name.lower():
            if delta > 0:
                print >> sys.stdout, 'send %s: no self promotion' % self._nick
                delta = -5
            elif delta < 0:
                print >> sys.stdout, 'send %s: Aww, cheer up, you can keep your point' % self._nick
                delta = 0

        try:
            # get the connection
            store = self._get_database_connection()

            # s will be None if none are found
            s = store.find(ScoreEntry, ScoreEntry.name == unicode(name)).one()

            if s is None:
                # create a new score entry
                s = ScoreEntry(name, delta, self._nick, self._to)
                store.add(s)
            else:
                # update the score entry we found
                s.nick = unicode(self._nick)
                s.value += delta
                s.date = datetime.now()
                
            # flush and commit
            store.flush()
            store.commit()
            
            self._log.debug('Score updated successfully...(nick: %s score: %d)' % (s.name, s.value))
       
        except Exception, err:
            self._log.warn('Score hook: %s' % err)

        return None

if __name__ == "__main__":
    hook = Score()
    sys.exit(hook.main())
