#!/usr/bin/env python

"""
This hook watches for people joining and checks to see if there
are any ping snipes that need to be delivered.
"""

import sys

# import hackabot utility classes
from hook import Hook
from models import Note

class Snipe(Hook):

    def __init__(self):

        # call the base constructor to set up everything
        super(Snipe, self).__init__('Snipe')

    def _deliver_snipes(self, to):
        # get the connection
        store = self._get_database_connection()

        # look up notes
        self._log.debug('looking for snipes aimed at: %s' % to)
        notes = store.find(Note, Note.nick_to == unicode(to))
        for note in notes:
            # deliver the snipe
            self._log.debug('sending snipe to: %s' % to)
            print >> sys.stdout, 'to %s' % to
            if note.chan != '':
                print >> sys.stdout, 'send ping from %s in %s on %s: %s' % (note.nick_from, note.chan, note.date, note.text)
            else:
                print >> sys.stdout, 'send ping from %s on %s: %s' % (note.nick_from, note.date, note.text)

            # remove the note
            store.remove(note)

        # store and commit
        store.flush()
        store.commit()

    def main(self):

        if self._event_type == 'join':
            self._deliver_snipes(self._nick)
        elif self._event_type == 'nick':
            self._deliver_snipes(self._to)

        return None

if __name__ == "__main__":
    hook = Snipe()
    sys.exit(hook.main())
