#!/usr/bin/env python

"""
This is a stats hook that tracks people coming and going.
"""

import sys

# import hackabot utility classes
from hook import Hook
from models import LogEntry

class Stats(Hook):

    def __init__(self):

        # call the base constructor to set up everything
        super(Stats, self).__init__('Stats')

    def main(self):
        try:
            # get the connection
            store = self._get_database_connection()

            # create the new log item
            e = LogEntry(self._nick, self._to, self._msg, 0, 'stats')

            # add it to the database
            store.add(e)

            # commit it
            store.flush()
            store.commit()
            
            self._log.debug('Stats successfully logged to database...(id: %d)' % e.id)
       
        except Exception, err:
            self._log.warn('Stats hook: %s' % err)

        return None

if __name__ == "__main__":
    hook = Stats()
    sys.exit(hook.main())
