#!/usr/bin/env python

"""
This is a stats hook that tracks people coming and going.
"""

import os
import sys

# import hackabot utility classes
from hook import Hook

class Stats(Hook):

    # Log queries
    Q = { 
        'mysql': { 
            'stats': ''
        },
        'sqlite': { 
            'stats' : 'INSERT INTO log (date, text, chan, nick, type) VALUES (date("now"),?,?,?,"stats")'
        }
    }

    def __init__(self):

        # call the base constructor to set up everything
        super(Stats, self).__init__('stats')

        # set up our queries
        self._queries = Stats.Q[self._db.lower()]

    def main(self):

        try:
            # get the connection
            conn = self._get_database_connection()

            # start a cursor
            c = conn.cursor()

            # run the query
            params = (self._msg, self._to, self._nick)
            c.execute(self._queries['stats'], params)

            # commit the change
            conn.commit()

            # clean up
            c.close()
            conn.close()

            self._log.debug('Stats successfully logged to database...')
       
        except Exception, err:
            self._log.warn('Stats hook: %s' % err)

        return None

if __name__ == "__main__":
    hook = Log()
    sys.exit(hook.main())
