#!/usr/bin/env python

"""
High five hook
"""

import re
import sys

# import hackabot utility classes
from hook import Hook

class YouRock(Hook):

    def __init__(self):

        # call the base constructor to set up everything
        super(YouRock, self).__init__('yourock')

    def main(self):

        if re.match(r'^.*\\o\/.*$', self._msg):
            print >> sys.stdout, 'sendnext'
            print >> sys.stdout, '%s++' % self._nick
            print >> sys.stdout, 'You ROCK!!'

        return None

if __name__ == "__main__":
    hook = YouRock()
    sys.exit(hook.main())
