INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("afaic", "AFAIC", "as far as I\'m concerned");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("afaicr", "AFAICR", "as far as I can recall");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("afaict", "AFAICT", "as far as I can tell");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("afaik", "AFAIK", "as far as I know");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("afair", "AFAIR", "as far as I recall");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("afaiu", "AFAIU", "as far as I understand");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("afd", "AFD", "away from desktop");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("afk", "AFK", "away from keyboard");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("afu", "AFU", "all fucked up");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("afw", "AFW", "away from window");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("aiu", "AIU", "as I understand");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("aiui", "AIUI", "as I understand it");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("aka", "AKA", "also known as");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("asaic", "ASAIC", "as soon as I can");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("asap", "ASAP", "as soon as possible");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("atm", "ATM", "at the moment");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("awol", "AWOL", "absent without official leave");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("aybabtu", "AYBABTU", "all your base are belong to us");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ayt", "AYT", "are you there");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("b/c", "B/C", "because");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("b/s", "B/S", "bullshit");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("b/w", "B/W", "between");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("bbiab", "BBIAB", "be back in a bit");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("bbl", "BBL", "[I\'ll] be back later");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("bbs", "BBS", "be back soon");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("bbt", "BBT", "be back tomorrow");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("bfd", "BFD", "big fucking deal");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("biab", "BIAB", "back in a bit");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("biaf", "BIAF", "back in a few");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("bialw", "BIALW", "back in a little while");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("bias", "BIAS", "back in a second");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("biaw", "BIAW", "back in a while");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("boatilas", "BOATILAS", "bend over and take it like a slut");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("bofh", "BOFH", "bastard operator from hell");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("bogahica", "BOGAHICA", "bend over, grab ankles, here it comes again");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("bohica", "BOHICA", "bend over here it comes again");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("brb", "BRB", "[I\'ll] be right back");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("bs", "BS", "bullshit");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("btdt", "BTDT", "been there, done that");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("btth", "BTTH", "boot to the head");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("btw", "BTW", "by the way");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("cmiiw", "CMIIW", "correct me if I\'m wrong");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("cnp", "CNP", "continued [in my] next post");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("cob", "COB", "close of business [day]");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("cots", "COTS", "commercial off-the-shelf");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("cya", "CYA", "see you around");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("d/l", "D/L", "download");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("diy", "DIY", "do it yourself");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("dkdc", "DKDC", "don\'t know, don\'t care");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("dstm", "DSTM", "don\'t shoot the messenger");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("dtrt", "DTRT", "do the right thing");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("dtwt", "DTWT", "do the wrong thing");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("dwim", "DWIM", "do what I mean");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("eg", "EG", "evil grin");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("emsg", "EMSG", "email message");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("eob", "EOB", "end of business [day]");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("eod", "EOD", "end of discussion");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("eol", "EOL", "end of life");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("etla", "ETLA", "extended three letter acronym");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ewag", "EWAG", "experienced wild-ass guess");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("faq", "FAQ", "frequently asked question");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("fcfs", "FCFS", "first come first served");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("figjam", "FIGJAM", "fuck I\'m good, just ask me");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("fiik", "FIIK", "fuck[ed] if I know");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("fiir", "FIIR", "fuck[ed] if I remember");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("fm", "FM", "fucking magic");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("foad", "FOAD", "fall over and die");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("fsdo", "FSDO", "for some definition of");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("fsvo", "FSVO", "for some value of");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ftfm", "FTFM", "fuck the fuckin\' manual!");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("fubar", "FUBAR", "fucked up beyond all recognition");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("fud", "FUD", "fear, uncertainty and doubt");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("fwiw", "FWIW", "for what it\'s worth");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("fyi", "FYI", "for your information");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("g", "G", "grin");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("g/c", "G/C", "garbage collect");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("gac", "GAC", "get a clue");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("gal", "GAL", "get a life");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("gigo", "GIGO", "garbage in, garbage out");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("gmta", "GMTA", "great minds think alike");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("gtfo", "GTFO", "get the fuck out");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("gtg", "GTG", "got to go");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("hand", "HAND", "have a nice day");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("hhis", "HHIS", "hanging head in shame");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("hica", "HICA", "here it comes again");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("hth", "HTH", "hope this helps");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("iac", "IAC", "in any case");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ianal", "IANAL", "I am not a lawyer");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ic", "IC", "I see");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("icbw", "ICBW", "I could be wrong");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("iccl", "ICCL", "I couldn\'t care less");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ihafc", "IHAFC", "I haven\'t a fucking clue");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ihbw", "IHBW", "I have been wrong");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ihnfc", "IHNFC", "I have no fucking clue");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("iianm", "IIANM", "if I am not mistaken");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("iirc", "IIRC", "if I recall correctly");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("iiuc", "IIUC", "if I understand correctly");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("imao", "IMAO", "in my arrogant opinion");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("imco", "IMCO", "in my considered opinion");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("imho", "IMHO", "in my humble opinion");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("imnsho", "IMNSHO", "in my not so humble opinion");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("imo", "IMO", "in my opinion");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("iow", "IOW", "in other words");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("irl", "IRL", "in real life");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("isagn", "ISAGN", "I see a great need");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("istm", "ISTM", "it seems to me");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("istr", "ISTR", "I seem to recall");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("itym", "ITYM", "I think you mean");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("iwbni", "IWBNI", "it would be nice if");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("iyss", "IYSS", "if you say so");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("j/k", "J/K", "just kidding");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("jhd", "JHD", "just hit ``delete\'\");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("jic", "JIC", "just in case");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("jk", "JK", "just kidding");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("jmo", "JMO", "just my opinion");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("jtlyk", "JTLYK", "just to let you know");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("kiss", "KISS", "keep it simple, stupid");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("kita", "KITA", "kick in the ass");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("knf", "KNF", "kernel normal form");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("l8r", "L8R", "later");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("lart", "LART", "luser attitude readjustment tool (ie, hammer)");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("lbnl", "LBNL", "last but not least");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ljbf", "LJBF", "let\'s just be friends");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("lmao", "LMAO", "laughing my ass off");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("lmso", "LMSO", "laughing my socks off");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("lol", "LOL", "laughing out loud");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ltns", "LTNS", "long time no see");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("mia", "MIA", "missing in action");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("motas", "MOTAS", "member of the appropriate sex");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("motos", "MOTOS", "member of the opposite sex");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("motss", "MOTSS", "member of the same sex");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("mtf", "MTF", "more to follow");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("myob", "MYOB", "mind your own business");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("n/m", "N/M", "never mind");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("nbd", "NBD", "no big deal");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("nfc", "NFC", "no fucking clue");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("nfi", "NFI", "no fucking idea");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("nfw", "NFW", "no fucking way");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("nih", "NIH", "not invented here");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("nmf", "NMF", "not my fault");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("nmp", "NMP", "not my problem");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("noyb", "NOYB", "none of your business");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("noyfb", "NOYFB", "none of your fucking business");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("np", "NP", "no problem");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("nrfpt", "NRFPT", "not ready for prime time");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("nrn", "NRN", "no reply necessary");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("oic", "OIC", "oh, I see");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("omg", "OMG", "oh, my god");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ot", "OT", "off topic");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("otl", "OTL", "out to lunch");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("otoh", "OTOH", "on the other hand");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ott", "OTT", "over the top");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ottomh", "OTTOMH", "off the top of my head");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("pebkac", "PEBKAC", "problem exists between keyboard and chair");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("pfo", "PFO", "please fuck off");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("pfy", "PFY", "pimply faced youth");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("pita", "PITA", "pain in the ass");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("pksp", "PKSP", "pound keys and spew profanity");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("png", "PNG", "persona non grata");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("pnp", "PNP", "plug and pray");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("poc", "POC", "point of contact");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("pola", "POLA", "principle of least astonishment");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("pols", "POLS", "principle of least surprise");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("pos", "POS", "piece of shit");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ppl", "PPL", "pretty please");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ptv", "PTV", "parental tunnel vision");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("qed", "QED", "quod erat demonstrandum");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rfc", "RFC", "request for comments");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rip", "RIP", "rest in peace");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rl", "RL", "real life");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rlc", "RLC", "rod length check");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rofl", "ROFL", "rolling on floor laughing");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("roflmao", "ROFLMAO", "rolling on floor laughing my ass off");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rotfl", "ROTFL", "rolling on the floor laughing");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rp", "RP", "responsible person");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rsn", "RSN", "real soon now");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rtfb", "RTFB", "read the fine/fucking book");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rtfc", "RTFC", "read the fine/fucking code");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rtfd", "RTFD", "read the fine/fucking documentation");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rtfm", "RTFM", "read the fine/fucking manual");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rtfmp", "RTFMP", "read the fine/fucking man page");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("rtfs", "RTFS", "read the fine/fucking source");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("scnr", "SCNR", "sorry, could not resist");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("sep", "SEP", "someone else\'s problem");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("sfa", "SFA", "sweet fuck all");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("shid", "SHID", "slaps head in disgust");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("simca", "SIMCA", "sitting in my chair amused");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("smlsfb", "SMLSFB", "so many losers, so few bullets");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("smop", "SMOP", "simple matter of programming");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("snafu", "SNAFU", "situation normal, all fucked up");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("snert", "SNERT", "snot-nosed egotistical rude teenager");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("snmp", "SNMP", "sorry, not my problem");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("snr", "SNR", "signal to noise ratio");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("so", "SO", "significant other");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("sob", "SOB", "son of [a] bitch");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("sol", "SOL", "shit out [of] luck");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("sop", "SOP", "standard operating procedure");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ssia", "SSIA", "subject says it all");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("stfa", "STFA", "search the fucking archives");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("stfu", "STFU", "shut the fuck up");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("stfw", "STFW", "search the fucking web");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("sus", "SUS", "stupid user syndrome");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("swag", "SWAG", "silly, wild-assed guess");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("swahbi", "SWAHBI", "silly, wild-assed hare-brained idea");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("swmbo", "SWMBO", "she who must be obeyed");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("tanstaafl", "TANSTAAFL", "there ain\'t no such thing as a free lunch");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("tbc", "TBC", "to be continued");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("tbd", "TBD", "to be {decided,determined,done}");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("tbomk", "TBOMK", "the best of my knowledge");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("thnx", "THNX", "thanks");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("thx", "THX", "thanks");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("tia", "TIA", "thanks in advance");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("tinc", "TINC", "there is no cabal");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("tla", "TLA", "three letter acronym");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("tlb", "TLB", "translation lookaside buffer");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("tma", "TMA", "too many abbreviations");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("tmi", "TMI", "too much information");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("tnf", "TNF", "The NetBSD Foundation");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("toefl", "TOEFL", "test of english as a foreign language");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("tptb", "TPTB", "the powers that be");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("trt", "TRT", "the right thing");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ttbomk", "TTBOMK", "to the best of my knowledge");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ttfn", "TTFN", "ta ta for now");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ttyl", "TTYL", "talk to you later");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("twiavbp", "TWIAVBP", "the world is a very big place");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ty", "TY", "thank you");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("tyvm", "TYVM", "thank you very much");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("u/l", "U/L", "upload");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("utsl", "UTSL", "use the source, Luke");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("veg", "VEG", "very evil grin");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("w/", "W/", "with");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("w/o", "W/O", "without");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("wag", "WAG", "wild-ass guess");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("wb", "WB", "welcome back");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("wfm", "WFM", "works for me");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("wibni", "WIBNI", "wouldn\'t it be nice if");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("wip", "WIP", "work in progress");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("woftam", "WOFTAM", "waste of fucking time and money");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("wombat", "WOMBAT", "waste of money, brain, and time");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("wrt", "WRT", "with respect to");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("wtf", "WTF", "{what,where,who,why} the fuck");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("wth", "WTH", "{what,where,who,why} the hell");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("wysiwyg", "WYSIWYG", "what you see is what you get");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("yalimo", "YALIMO", "you are lame, in my opinion");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("yhbt", "YHBT", "you have been trolled");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("yhl", "YHL", "you have lost");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ykwim", "YKWIM", "you know what I mean");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("yma", "YMA", "yo momma\'s ass");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("ymmv", "YMMV", "your mileage may vary");
INSERT INTO wtf ("acronym_i", "acronym", "text") VALUES ("yw", "YW", "you\'re welcome");
