#!/usr/bin/python

##HACKABOT_HELP##
# Roll a single 20-sided die
# !1d20
##HACKABOT_HELP##

import string
import sys
import os
import random
from command import *

class OneDTwenty(Command):
    """
    An example command using new command writing tools.
    """

    def __init__(self):

        # call the base constructor to set up everything
        super(OneDTwenty, self).__init__()

    def main(self):
        """
        example handler function
        """

        # give sendnext command
        print >> sys.stdout, "sendnext"

        # dump the data we parsed
        print >> sys.stdout, random.randint(1,20)

        return None


if __name__ == "__main__":
    cmd = OneDTwenty()
    sys.exit(cmd.main())
