#!/usr/bin/env python

"""
Ponies hook
"""

import re
import sys

# import hackabot utility classes
from hook import Hook

class Ponies(Hook):

    def __init__(self):

        # call the base constructor to set up everything
        super(Ponies, self).__init__('ponies')

    def main(self):

        # prevent a loop from occurring
        if self._nick.lower() == self._user.lower():
            return None

        if re.match(r'^.*(ponies|pony).*$', self._msg, re.IGNORECASE):
            print >> sys.stdout, 'send OMG!!! Ponies!!!'

        return None

if __name__ == "__main__":
    hook = Ponies()
    sys.exit(hook.main())
